### ISSUE TITLE
Default path is not current project

### ISSUE THREAD

**Issue by Vocal** [Osmose/advanced-open-file#1]
Hi Osmose.
I have a problem. 
When i don't open any file then it not show project root folder.
Please fix it. 
Thanks.
![bug](https://cloud.githubusercontent.com/assets/5045717/8133069/16073088-1150-11e5-988f-f493b5a54fd5.png)

**Comment by Osmose** [comment]
Whoops, somehow was not watching my own repo, doh!

I'll see if I can replicate this within the next few days. Thanks for the report!

**Comment by Osmose** [comment]
@Vocal I believe this is fixed, can you verify? If not, please reopen this issue. Thanks!

**Comment by Vocal** [comment]
@Osmose it fixed, thanks ! :+1:
