### ISSUE TITLE
Add emacs keybinds for up/down when selecting file

### ISSUE THREAD

**Issue by nomatics** [Osmose/advanced-open-file#11]
Proposed add for Emacs ctrl-n and ctrl-p for selecting next/prev file in list. 
Also, ctrl-i/ctrl-k are popular movement key combos.

**Comment by Osmose** [comment]
Not a bad idea! Your PR looks good, but I think rather than hard-coding the key combinations, we'd be better off to register some [commands](https://atom.io/docs/api/v1.0.7/CommandRegistry), use them for the movement and register the extra keys in the keymap file.

How does that sound?
