### ISSUE TITLE
File/directories not highlighting when using keyboard to navigate through file list on Windows

### ISSUE THREAD

**Issue by jhslinkman** [Osmose/advanced-open-file#111]
Steps to reproduce:

0. In windows
1. `ctrl-alt-o` in any file
2. Use cursor keys to traverse file list

I believe this is because `\`s are being escaped in [lib/view.js#L384](https://github.com/Osmose/advanced-open-file/blob/master/lib/view.js#L384) but that the query selector used to determine which path is selector on keyboard up/down does not reflect this.

**Comment by Osmose** [comment]
Fixed by 074475647a9ee420f7ce2b04a560134a62204589. Thanks!
