### ISSUE TITLE
Page Up and Page Down keys for navigation in list

### ISSUE THREAD

**Issue by AlexWayfer** [Osmose/advanced-open-file#120]
Enable Page Up and Page Down keys for navigation in list, please 😇

**Comment by Osmose** [comment]
There's actually commands you can bind for this yourself in your keybindings file:

```cson
'.advanced-open-file atom-text-editor':
  'pagedown': 'advanced-open-file:move-cursor-down'
  'pageup': 'advanced-open-file:move-cursor-up'
```

Hope that helps!

**Comment by AlexWayfer** [comment]
Oh, no! Page Down/Up should not move one position up or down, and at the end or beginning of the list.
Does `advanced-open-file` have these commands?

**Comment by Osmose** [comment]
Ah, we don't have commands for those.

**Comment by Osmose** [comment]
I don't really have bandwidth to work on this myself, but I'll review/merge/release a PR that adds this!

**Comment by Osmose** [comment]
Fixed by the PRs mentioned above. :D
