### ISSUE TITLE
I hit enter to create directory and not be created

### ISSUE THREAD

**Issue by JuanVqz** [Osmose/advanced-open-file#126]
I hit enter to create directory in the path that don`t exist and not be created

**Comment by Osmose** [comment]
Thanks for the report!

I'm unable to replicate this locally. Here's what I did:

1. Open the advanced-open-file dialog.
2. Enter a path that doesn't currently exist, that ends in a slash (i.e. `/tmp/does/not/exist/`).
3. Hit Enter.

For me, that creates a directory named `/tmp/does/not/exist/`. Are you doing something different from that process? What platform are you on? Are you on the latest Atom/Advanced-Open-File version?

**Comment by JuanVqz** [comment]
Thanks for your help.

if I put a directory that ends in  carpet/ hit enter! and does nothing.

atom version 1.10.2, yes I use advanced-open-file, My SO Mac "El capitan".

**Comment by Osmose** [comment]
Ah, so it's not just directories. Interesting.

Can you open the devtools (View -> Developer -> Toggle Developer Tools), open the Console in the devtools, then record the error happening again with the console in view? I'm wondering if there's an error that we're not catching and showing a notification for. Also, does this happen in _any_ directory, like even ones outside of that project (like `/tmp/foobar/blah.php`)?

**Comment by snapjosh** [comment]
I'm having a similar problem attempting to create files:
OS X El Capitan 10.11.5
Atom 1.14.3 x64
advanced-open-file 0.16.5

I open advanced-open-file using alt-cmd-o, type in non existing file name, hit enter, and nothing happens. I've tried full paths and relative. Nothing happens.

Beyond this, file matching for opening files is horribly off. Example: a search for a file (that does exist) titled 'contact-info.js' returned results for 'entity-type.html' and 'entity-type.js' despite none of the words from 'conact-info.js' being anywhere in the name or path of 'entity-type.js'. Very frustrating. All I really want this to do is create new files with alt-cmd-n like the deprecated versions. :(
