### ISSUE TITLE
Option to hide full project path 

### ISSUE THREAD

**Issue by lucaskatayama** [Osmose/advanced-open-file#129]
Hi,
I think it would be great to have an option to hide the full path to project... 

Instead of having:

/home/user/path/to/project/

Have something like

./project/

Thanks

**Comment by Osmose** [comment]
It's not super-clear from the preferences page for the package, but you can set the default input value to empty, and relative paths refer to the project directory, which accomplishes roughly what you want.

Hope that helps! Let me know if that isn't quite what you want. :D

**Comment by lucaskatayama** [comment]
Well works partially...
When I have a project with too many dir levels `path1/path2/path3/path4/index.js` , I'll need to fill all paths.
I was trying to create a file inside the same index.js folder... So using option **active file's directory** worked... But getting system path (/home/user/dev/git/project ...) annoys me ...

For me... If you open a project... The context should be relative to that project ...

Just an idea...

**Comment by Osmose** [comment]
So you want active file's directory, but relative to the project directory, right? So like if you were editing `/Users/foo/project/bar/bazz/biff/bam.txt`, and the project was in `/Users/foo/project/bar`, you want the pre-populated path to be `bazz/biff/`?

What should happen if you're editing a file outside of the current project?

**Comment by lucaskatayama** [comment]
Yeah ...you got it right...

Editing a file outside IS a problem... Atom has two "modes" like an IDE and like a Text Editor....

I think if i'm editing a file outside... it should show the full path...
