### ISSUE TITLE
popup path input is NOT wide enough.

### ISSUE THREAD

**Issue by CodeAmend** [Osmose/advanced-open-file#140]
When I first installed this, it was wide and you can see the entire path, but since then I have installed new themes and now the width is like 25% of screen. This means that I cannot see the entire path. With Atom material it does not go off screen and as you add more paths it makes a new line to continue the large path. With isotope it does not. Perhaps you might say this is isotopes fault, but at least I would like to know what CSS is being afected so I can fix it myself. Thank you for such a nice package addition to Atom. 

my setup:
Atom 1.14.3
isotope ui

ISOTOP UI (this does not play nice)
<a href="http://i.imgur.com/ek5pmgK.png">
  <img src="http://imgur.com/ek5pmgKl.png" />
</a>

ATOM MATERIAL UI
<a href="http://i.imgur.com/3B2dehO.png">
  <img src="http://imgur.com/3B2dehOl.png" />
</a>

**Comment by alvis** [comment]
I have similar issue with [Dark Flat UI](https://atom.io/themes/dark-flat-ui). For this theme, the cause is that the theme introduces a max-height to `atom-text-editor[mini]`. Therefore, a quick fix for me is to overrule the style specifically for the path input. Here is my code injected to [Atom's stylesheet](https://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks):
```css
atom-panel div.advanced-open-file atom-text-editor.path-input {
  max-height: none;
}
```

This style would not target anything else but the path input box. So it is more-or-less a perfect solution, except the fact that you've to inject the code yourself. Probably it is good for advanced-open-file to include this css into the package.

**Comment by CodeAmend** [comment]
Thanks for the response!  Unfortunately, I was not successful with your method. I hope the author can take a look at this. **This is an actual bug.**

**Comment by iamstarkov** [comment]
@CodeAmend can you change the theme?

**Comment by iamstarkov** [comment]
and see if it works with other themes?

**Comment by iamstarkov** [comment]
i wouldnt say its **actual bug**, as far as it depends on a theme you use

**Comment by NDuggan** [comment]
@alvis suggested CSS didn't work for me either, but it was close.

@CodeAmend To get it to work with my active theme (Nucleus Dark) I used the following:

```
// Fix advanced-open-file input width
atom-panel div.advanced-open-file atom-text-editor.path-input {
  height: auto;
}
```

**Comment by cavaunpeu** [comment]
@alvis solution worked for me. Using Atom Dark.

**Comment by RodideBoer** [comment]
I have the same with Atom Dark theme. It is pretty annoying.
Workaround by @alvis works, but it is pretty lame to have the input box grow vertically like that. It would be better if the input box would just scroll to show the caret (where you're typing).

**Comment by CodeAmend** [comment]
I agree with the scroll idea! +1

**Comment by aliusmiles** [comment]
Looks like scroll has been implemented :)
atom 1.17.0
advanced-open-file 0.16.6
native-ui 0.20.6

**Comment by NDuggan** [comment]
Can confirm scroll is working for me in `Atom 1.17.0` (before and after removing the suggested CSS fix above).

Great work!

**Comment by RodideBoer** [comment]
It seems to work here too. Had to double check, because I didn't see the caret, but after starting to type it did scroll to the end. Could use a little bit of extra white space at the end , but it works!

Good job people.

**Comment by iamstarkov** [comment]
so issue can be closed? @CodeAmend

**Comment by Osmose** [comment]
Sounds like it based on the reports. Sorry for not spending time fixing this; I haven't made time for AOF in a while. But hooray for the problem fixing itself!

**Comment by CodeAmend** [comment]
Sorry for not answering, I didn't realize I had a message. I cannot reproduce this right now. But, because this is such an amazing plugin, I will let you know if I get another conflict.
