### ISSUE TITLE
Doesn't create new file OS 10.12

### ISSUE THREAD

**Issue by aprofromindia** [Osmose/advanced-open-file#141]
In Mac OS 10.12 , I press CMD + ALT + O to open the file open window, but its doesnt create a new file if I guide a nonexistent address (e.g. build/index.js), I am using Atom 1.14 and Advanced open file - latest version.

**Comment by aprofromindia** [comment]
worked after reinstall

**Comment by Osmose** [comment]
Weird. Sorry I didn't get to this earlier. And thanks for following up and closing the issue! :D
