### ISSUE TITLE
Create numbered files using CTRL+N (like notepad++)

### ISSUE THREAD

**Issue by JerryGoyal** [Osmose/advanced-open-file#142]
How can I map CTRL+N to shortcut to create new files with numbers. By default it creates "untitled" name files when using shortcut to create new file.
Actually, I want to switch to Atom from Notepad++. I'm really missing the feature of creating numbered files like "new 1", "new 2", "new 3" instead of same "untitled" file.

It's a really good and handy feature.

Pardon me if this is not the correct place to ask for this feature/implementation.

**Comment by Osmose** [comment]
Thanks for the suggestion!

Creating new files with numbered names doesn't fit with this particular package (advanced-open-file), but it could be another package. Your best bet is to ask on the [forums](https://discuss.atom.io/) to see if there's an existing package that does this.

**Comment by JerryGoyal** [comment]
Thanks. After searching for +1 hour I found the package "tab title" (https://github.com/erikjansson/atom-tab-title) which does the same job :)
