### ISSUE TITLE
Feature request: auto open file

### ISSUE THREAD

**Issue by slavaGanzin** [Osmose/advanced-open-file#148]
Hello awesome plugin which use for a long time! Thanks

I want aof to automatically open file if i narrowed search to a single file.

Having folder with files:
one.py
two.py
three.py

Now:
- write onepy
- press down
- press enter
- file open

Would be perfect:
- write one
- file open

Of course this shouldn't be default behaviour.

**Comment by slavaGanzin** [comment]
I found that this could be done with:
```
'.advanced-open-file atom-text-editor':
  'enter': 'advanced-open-file:confirm-selected-or-first'
```

Thanks!

**Comment by Osmose** [comment]
lol, glad that worked out for you :D
