### ISSUE TITLE
Add supported path with 'file://'

### ISSUE THREAD

**Issue by Eskander88** [Osmose/advanced-open-file#153]
Will be great add supporting for parsing path with 'file://'. 
Also a useful solution will be getting a source code when user input http-address

**Comment by Osmose** [comment]
Thanks for the suggestion!

I don't see much of a reason to include this in Advanced Open File vs another plugin specifically for this purpose, besides mild convenience. We can't really do partial matching or directory traversal for URLs in the same way we do for local directories, which means just a bare prompt to insert a URL is just as effective a UI.

So I don't think I'd accept a PR that added this. But, you should totally consider writing a plugin that does this, Atom has some UI bits that would make this pretty simple.
