### ISSUE TITLE
Duplicate File Option is Missing

### ISSUE THREAD

**Issue by hqasraful** [Osmose/advanced-open-file#155]
Dear Sir,
          I loved your package, but still something is missing. If I want to duplicate or rename
 a file, then option is not available. Hope will update it. Waiting for your swift responses. The following options are available in Sublime Text 3.
![capture](https://user-images.githubusercontent.com/7779509/48207792-6b9fc600-e397-11e8-9f67-7a92c8eb5e5b.PNG)

Thanks
Asraful Haque
hq.tranquil@gmail.com

**Comment by Osmose** [comment]
Thanks for the issue!

If I'm interpreting your screenshot correctly, those are command palette options to create a copy of a currently-open file, or to rename it, correct? 

Renaming a file is available in Atom in the command palette under the name "Tree View: Rename". You can open the command palette with <kbd>Cmd+Shift+P</kbd>.

There's also a "Tree View: Duplicate" available, although I've never used it so I dunno what it does.

In either case, neither of those things are really things I want advanced-open-file to support specifically, and integrating them into our current UI would be kinda difficult. So I'm going to close this, but hopefully the existing commands will work for you.

**Comment by hqasraful** [comment]
Thank you for your swift response. But it would be better if all file related options are available though command palette with 
> Cmd+Shift+P


just similar to the Sublime Text IDE.

Asraful Haque
hq.tranquil@gmail.com

**Comment by Osmose** [comment]
> But it would be better if all file related options are available though command palette with

Rename and duplicate are available via that command palette, though.
