### ISSUE TITLE
Function.extractParams is deprecated.

### ISSUE THREAD

**Issue by LJP88** [Osmose/advanced-open-file#157]
Assigning custom properties to a marker when creating/copying it is
deprecated. Please, consider storing the custom properties you need in
some other object in your package, keyed by the marker's id property.
```
Function.extractParams (<embedded>:79365:20)
MarkerLayer.markPosition (<embedded>:80028:30)
DisplayMarkerLayer.markBufferPosition (<embedded>:135676:58)
TextEditor.markBufferPosition (<embedded>:4678:42)
Generator.restoreCursor (C:\Users\LENOVO\.atom\packages\auto-header\lib\generator.coffee:13:28)
Generator.sync (C:\Users\LENOVO\.atom\packages\auto-header\lib\generator.coffee:56:19)
```

**Comment by Osmose** [comment]
Thanks for the issue!

Is this the right repo? The package in your traceback is `auto-header` and I can't find any instances of `extractParams` in our code.

**Comment by iamstarkov** [comment]
yeah, I vote for this issue to be closed

**Comment by Osmose** [comment]
Feel free to reopen if I'm wrong. Thanks again!
