### ISSUE TITLE
New file is created in the wrong location.

### ISSUE THREAD

**Issue by wlwl2** [Osmose/advanced-open-file#158]
OS: Using macOS Catalina 10.15.1 (19B88). 

Typing in the filename inside a new folder and then pressing enter will create the new file in the folder just before/outside of the new folder.

What I would expect to happen:
A new file is created following the path I entered.

**Comment by wlwl2** [comment]
Sorry, I just remembered how this works, just need to save the file. I think this is intended behaviour.

**Comment by Osmose** [comment]
If you prefer it to create files immediately, there's a setting for that too:

![Screen Shot 2020-03-14 at 1 08 50 AM](https://user-images.githubusercontent.com/193106/76677858-64db2180-6590-11ea-8282-b8afb18d7f60.png)

Hope that helps!
