### ISSUE TITLE
Path Autocomplete [Feature Request]

### ISSUE THREAD

**Issue by Miladiouss** [Osmose/advanced-open-file#159]
Please implement path autocomplete in the editor environment. For example, as the user is coding, they might want to give the path to a particular file. Then they will start typing `"~/Desk"` or `"./my"` within their code. By pressing a keybinding such as shift+tab, your menu of relevant directories would be listed at the cursor.  

Thanks.

**Comment by Osmose** [comment]
You're talking about path completion within the editor itself, right? That's not in scope for this plugin, we're only concerned about the file open dialog we have.

Closing this as I wouldn't accept a PR adding it, but thank you for the suggestion!
