### ISSUE TITLE
Clearing path first frustrates Helm directory switching

### ISSUE THREAD

**Issue by posita** [Osmose/advanced-open-file#18]
To reproduce:

* Activate Helm-style directory switching in the preferences
* Open the advanced-open-file dialog
* With the cursor focus on the path, do select-all (e.g., `CTRL-a` or `⌘-a` on OS X)
* Type `~/`

I expected the path to be replaced with an absolute path to my home directory.

No replacement happened.

If you type `~/` again (i.e., `~/~/`), then the absolute path to the home directory is replaced.

**Comment by Osmose** [comment]
Aha, good catch! I agree with your expectations and will get on fixing it when I can. Thanks!

**Comment by Osmose** [comment]
This should be fixed in master, and hopefully will get released soon in `v0.9.0`. Thanks for the report!

(If you're willing to test it out and verify that it's fixed that'd be super-userful too!)

**Comment by posita** [comment]
LGTM :+1: (See #48, however.)
