### ISSUE TITLE
Fast directory switch to ~ and /

### ISSUE THREAD

**Issue by ineu** [Osmose/advanced-open-file#2]
In Helm it's possible to jump to the home or root directory by typing ~ and / after trailing slash. This is handy as it allows to quickly escape from deeply nested project structure to edit some config file. Is it possible to implement such functionality in AOF?

**Comment by Osmose** [comment]
Sure!

I've never used Helm myself (but I've heard of it), so a question: After you type those two things, does it replace the existing path in the text input completely, or does it leave it in and just change the current directory listing to the home directory?

**Comment by ineu** [comment]
It replaces existing path. So, assuming your path ends with a slash:
1. You type `/` (one more slash): path is reset to /
2. You type `~/`: path is reset to your home directory

**Comment by ineu** [comment]
Works great, thank you!

**Comment by Osmose** [comment]
No problem, thanks for using it!
