### ISSUE TITLE
New File Not Found With Fuzzy Finder

### ISSUE THREAD

**Issue by gibsjose** [Osmose/advanced-open-file#25]
New files created with `advanced-open-file` are not indexed by the built-in Atom Fuzzy Finder. Not sure if this is an issue with Fuzzy Finder or with this, but it is something you may want to look into.

**Comment by Osmose** [comment]
Huh, you're right. I actually get the same bug even when creating a new file using the menus (IE not with anything from advanced-open-file).

There's https://github.com/atom/fuzzy-finder/issues/119 and https://github.com/atom/fuzzy-finder/issues/30 filed with the fuzzy-finder, so I think this is a bug on their part.

I'm marking this as closed, but it'd be great if you could verify if you also hit the bug when creating a new file and saving it outside of advanced-open-file. Thanks for the report!

**Comment by gibsjose** [comment]
Verified! Must be a bug with FF then. Thanks for looking into it!
