### ISSUE TITLE
Add emitter and emit event when files are created

### ISSUE THREAD

**Issue by Osmose** [Osmose/advanced-open-file#28]
A continuation of the request from PR #16.

@Krzysztof-Cieslak Did you want the event to be triggered only when a file is created, or when a file is opened? If the "Create files instantly" preference is disabled, then the file isn't created until it is saved, and we can't really emit an event in that case.

**Comment by Krzysztof-Cieslak** [comment]
This is unfortunate limitation but don't think we can do anything about it. As for now I would emit 2 events - one for "on file opened", second one "on file created" (if "Create files instantly" is enabled). I'm actually mostly interested in this second case, even if it requires some preferences setup.  

What do You think about it? It would requires updates in PR.

**Comment by Osmose** [comment]
> What do You think about it? It would requires updates in PR.

Sounds fine to me!
