### ISSUE TITLE
Difference Unix/Windows paths for adding project folders

### ISSUE THREAD

**Issue by Traverse** [Osmose/advanced-open-file#30]
Hey I just noticed a small difference between Unix and Windows paths for adding project folders so I made some screenshots because they show exactly what I mean.

![windowspath](https://cloud.githubusercontent.com/assets/7240988/9700057/ae74e7aa-53f6-11e5-8b87-99b0de85fc66.jpg)
![unixpath](https://cloud.githubusercontent.com/assets/7240988/9700074/66815388-53f7-11e5-8d6b-380d0ac8fe31.jpg)

So basically with a standard Windows path the plus doesn't show with a Unix path it does.

advanced-open-file 0.9.1
Atom 1.0.11
Windows 7 x64

**Comment by Osmose** [comment]
Thanks for the report!

I have a branch up at https://github.com/Osmose/advanced-open-file/tree/detect-folders-better with a possible fix but no easy way to test it. Could you verify if it works or not?

**Comment by Traverse** [comment]
Hey I just tested it and I'm not sure what the intended behavior is now. Is it intended that you can't add folders inside the current project folder as a new project folder? If so then this fix works if that's not the intended behavior then this fix breaks it for both Windows and Unix paths so depending on what the intended behavior is I can't say at the moment if it's fixed or not.

**Comment by Osmose** [comment]
> Is it intended that you can't add folders inside the current project folder as a new project folder?

It is, because you used to be unable to add subfolders of project folders as new project folders. However, I just tested it and it seems to work now, so I'll followup with another fix to remove the logic that detects that.

Thanks for verifying!

**Comment by Osmose** [comment]
Merged. The fix should go out soon after I do a release within the next day or two. Thanks for the testing and report!

(And I filed https://github.com/Osmose/advanced-open-file/issues/38 about showing the buttons on folders that can now be added as project folders.)
