### ISSUE TITLE
Idea: Helm-style alias for project root?

### ISSUE THREAD

**Issue by JesseLeite** [Osmose/advanced-open-file#32]
You currently have these options for fast directory switching:

- Adding an extra slash (e.g. `/`) will switch to the filesystem root.
- Adding a tilde and a slash (e.g. `~/`) will switch to the current user's home directory.

What do you think about an option for switching to project root?  (Sublime's advanced-new-file package uses a colon `:` for switching to project root or top level folder in sidebar.)

**Comment by Osmose** [comment]
Oh, nice! At that point then I'd remove the "helm-style" name and just call it "Fast directory switching".

**Comment by JesseLeite** [comment]
Beauty, thanks! Looking forward to release :)
