### ISSUE TITLE
Uncaught TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by AJRodz88** [Osmose/advanced-open-file#37]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Microsoft Windows 10 Home
**Thrown From**: [advanced-open-file](https://github.com/Osmose/advanced-open-file) package, v0.9.2

### Stack Trace

Uncaught TypeError: Cannot read property 'forEach' of undefined

```
At /C:/Users/AlexJ/.atom/packages/advanced-open-file/lib/advanced-open-file-view.coffee:297

TypeError: Cannot read property 'forEach' of undefined
    at C:\Users\AlexJ\.atom\packages\advanced-open-file\lib\advanced-open-file-view.coffee:179:14
    at FSReqWrap.oncomplete (fs.js:77:15)
```

### Commands

```
     -0:02.9.0 advanced-open-file:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "advanced-open-file": {
    "createFileInstantly": true,
    "defaultInputValue": "Project root"
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.9.2
atom-alignment, v0.12.1
change-case, v0.6.0
emmet, v2.3.12
jshint, v1.7.0

# Dev
No dev packages
```

**Comment by Osmose** [comment]
Thanks for the report!

I just put up a pull request / branch https://github.com/Osmose/advanced-open-file/pull/39 that adds a more detailed error message instead of failing when this happens. Would you be able to pull down that branch and test it out to see what specific error message you get? That'd help determine if you're simply running into a permissions issue, in which case the PR is the solution, or if there's another problem that we have to handle in addition to showing the message.

**Comment by Osmose** [comment]
I released a rewrite that made huge changes to the code throwing this error, and #64 changes the plugin to ignore all errors when stat-ing files, which includes permission errors. Given those two things, I'm marking this closed, but feel free to reopen and clarify if the new version is causing any more issues. Thanks!

**Comment by Norfeldt** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [advanced-open-file](https://github.com/Osmose/advanced-open-file) package, v0.14.1


### Stack Trace

Uncaught TypeError: Cannot read property 'forEach' of undefined

```
At /C:/Users/Norfeldt/.atom/packages/advanced-open-file/lib/advanced-open-file-view.coffee:315

TypeError: Cannot read property 'forEach' of undefined
    at C:\Users\Norfeldt\.atom\packages\advanced-open-file\lib\advanced-open-file-view.coffee:315:18
    at FSReqWrap.oncomplete (fs.js:82:15)
```

### Commands

```
     -7:56.3.0 tree-view:add-folder (div.header.list-item)
  2x -5:40 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  2x -5:27.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -4:12.5.0 application:open-folder (atom-text-editor.editor.is-focused)
     -4:03.5.0 advanced-open-file:toggle (atom-text-editor.editor.is-focused)
     -3:59.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:50.8.0 advanced-open-file:toggle (atom-text-editor.editor.is-focused)
  3x -3:47.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:43 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -3:27.9.0 tree-view:remove (span.name.icon.icon-file-text)
  2x -1:37 advanced-open-file:toggle (atom-text-editor.editor.is-focused)
     -0:27.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:25.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tidy-markdown"
    ],
    "themes": [
      "atom-light-ui",
      "solarized-dark-syntax"
    ]
  },
  "advanced-open-file": {
    "createFileInstantly": true,
    "createDirectories": true
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.14.1
angularjs, v0.3.4
atom-beautify, vundefined
atom-ng-attr-hint, v2.1.0
autoclose-html, v0.20.0
change-case, v0.6.0
emmet, v2.4.1
file-type-icons, v0.7.4
foldingtext-markdown, v1.3.2
jshint, v1.8.3
livereload, v0.4.4
markdown-preview-opener, v0.1.1
minimap, v4.19.0
open-in-browsers, v0.0.7
preview-plus, v1.2.6

# Dev
No dev packages
```

**Comment by Norfeldt** [comment]
All I tried was to create a folder called view by CTRL`+`alt`+`o` and then write `views\`
