### ISSUE TITLE
Support Ido-inspired C-l to delete a directory component

### ISSUE THREAD

**Issue by artagnon** [Osmose/advanced-open-file#43]
The alt-backspace doesn't delete the '/' along with the path component, effectively making the user do double the number of keystrokes to strip path components.

**Comment by Osmose** [comment]
Ohhh, good idea! I dunno if I want to co-opt alt-backspace (at least on OSX) though, because it already has common semantics of deleting a word rather than a path component.

Are there common keyboard shortcuts for this on different platforms?

**Comment by Osmose** [comment]
Oh, I see from your PR now, you meant that alt-backspace wasn't enough, and added C-l. I get it now!
