### ISSUE TITLE
Path input field height shrinks temporarily when typed path is "${HOME}/"

### ISSUE THREAD

**Issue by posita** [Osmose/advanced-open-file#48]
I found this while verifying #18 on OS X. Let's say my username is `xyz`, and my home directory is `/Users/xyz`. If I type `/Users/xyz/` (note the trailing slash), in the advanced open file dialog, the input field height shrinks to almost nothing:

![screen shot 2015-09-17 at 21 28 03](https://cloud.githubusercontent.com/assets/222581/9952007/f5727a14-5d83-11e5-90de-4a63b1cc0bac.png)

This also happens immediately after expanding `~/` to `/Users/xyz/` as well.

It re-expands to the original height if any change is made (e.g., appending `Desktop/`.

What's odd is that this doesn't seem to happen for any other directory (e.g., `/Users/`, `/Users/xyz/Desktop/`, etc.).

**Comment by posita** [comment]
It seems to also shrink for any path that (ultimately) resolves to `${HOME}/`, e.g.:

* `/Users/xyz/`
* `/Users/xyz/./`
* `/Users/xyz/../xyz/`
* `/usr/bin/../../bin/../Users/xyz/`

Note that it doesn't happen for this:

* `/thisdirectorydoesnotexist/../Users/xyz/`

**Comment by Osmose** [comment]
This looks suspiciously like #41; shrinkage due to the amount of files in the directory making the file list larger than the height of the window. Can you confirm if it's that or if it's something unrelated?

If it is, then the current master should fix the issue.

**Comment by posita** [comment]
Whoops! I missed that one, and you're right. If I move enough files out of my home directory, the problem disappears. Closing as a duplicate of #41.

**Comment by Osmose** [comment]
Cool, thanks for confirming! The 0.10.0 release yesterday has the fix.
