### ISSUE TITLE
Directory listing only working with backslashes

### ISSUE THREAD

**Issue by Traverse** [Osmose/advanced-open-file#50]
Hey I just updated to 0.10.0 and directories are only being shown for me using backslashes, forward slashes list nothing. So things like `C:/`, `/`, `~/`, `:/` show nothing whilst `C:\`, `\`, `~\`, `:\` do show the directory list, I'm using Atom 1.0.15 on W7x64.

**Comment by Osmose** [comment]
Thanks for the report.

How much of a problem is this for you? I ask because, as part of a refactoring I'm slowly working on, I'm trying to abstract away all the path handling in a way that will make issues like this really easy to address. But that will probably take a few more weeks to land, and I don't want to leave you hanging for too long if this is a big issue for you.

What should we do?

**Comment by Traverse** [comment]
I don't mind waiting till you're done refactoring. Also ignoring this issue for now will give you a bit more time to work on the refactoring which is in my opinion better to spend your time on seeing as it'll make this issue really easy to fix as you said :wink:

**Comment by pimentel** [comment]
Thanks for the hard work.

I too would like this feature. I am working on mac and would really like to use `~/`

**Comment by Osmose** [comment]
> I too would like this feature. I am working on mac and would really like to use ~/

You should be able to use that now, this issue is Windows-specific. Is it not actually working for you?

**Comment by pimentel** [comment]
@Osmose nope, I can't use `~/`. is there anything I can provide to help with the bug report?

**Comment by Osmose** [comment]
@pimentel If you can file a new issue with the details of exactly what you're doing and what you're expecting to happen (for example: "I open the dialog, the path in the input box is /foo/bar/baz, I type ~/ so that it is /foo/bar/baz/~/ and no files are listed") as well as the settings you have for the package, that'd be helpful in figuring out if I can replicate your issue. Thanks!

**Comment by Osmose** [comment]
Also, just an update, I'm close to being on-par with the current version of the package with the rewrite, just gotta add directory shortcuts and some settings, and then I'll put it up in a branch for people to test out while I work out how to write tests.

I'm not 100% happy with all the stuff in the rewrite but I think it's a definite improvement, or, at the very least, it's shaped more like me, which will make it easier to work with for me. :D

**Comment by Traverse** [comment]
Good to hear that it's coming along, will do some testing once the branch is up :wink::+1:

**Comment by Osmose** [comment]
Just released the rewrite! It should guess which path separator to use based on the existing path. Does it work better for you? Is there still anything we need to improve?

**Comment by Traverse** [comment]
It seems to be working I do however get an error when I open the dialog and start typing `C:/` it throws an error right after I type the slash. 

Also on windows the fast directory switching is a bit annoying mostly because whenever I type `C:/` it immediately completes it to the project root which you might not want. So maybe add a check if there's any characters in front of `:/`.

Besides this it's looking good it feels a lot more responsive now and the paths do indeed detect the separator so awesome job :+1: 

------

**Atom Version**: 1.1.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [advanced-open-file](https://github.com/Osmose/advanced-open-file) package, v0.12.0


### Stack Trace

Uncaught Error: EBUSY: resource busy or locked, stat 'C:\hiberfil.sys'

```
At /C:/Users/Tom/.atom/packages/advanced-open-file/lib/models.js:197

Error: EBUSY: resource busy or locked, stat 'C:\hiberfil.sys'
    at Error (native)
    at fs.statSync (fs.js:854:18)
    at Object.fs.statSync (ATOM_SHELL_ASAR.js:225:16)
    at Path.get (C:/Users/Tom/.atom/packages/advanced-open-file/lib/models.js:41:23)
    at Path.descriptor.get (C:/Users/Tom/.atom/packages/advanced-open-file/lib/utils.js:18:36)
    at Path.isDirectory (C:/Users/Tom/.atom/packages/advanced-open-file/lib/models.js:52:20)
    at C:/Users/Tom/.atom/packages/advanced-open-file/lib/view.js:196:62
    at Array.filter (native)
    at AdvancedOpenFileView.setPathList (C:/Users/Tom/.atom/packages/advanced-open-file/lib/view.js:196:40)
    at AdvancedOpenFileController.updatePath (C:/Users/Tom/.atom/packages/advanced-open-file/lib/controller.js:92:19)
    at AdvancedOpenFileController.pathChange (C:/Users/Tom/.atom/packages/advanced-open-file/lib/controller.js:71:14)
    at C:/Users/Tom/.atom/packages/advanced-open-file/lib/view.js:132:17
    at Emitter.module.exports.Emitter.emit (C:\Users\Tom\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at C:\Users\Tom\AppData\Local\atom\app-1.1.0\resources\app.asar\src\text-editor.js:181:32
    at Emitter.module.exports.Emitter.emit (C:\Users\Tom\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (C:\Users\Tom\AppData\Local\atom\app-1.1.0\resources\app.asar\src\display-buffer.js:297:20)
```

### Commands

```
     -2:08.0 click (a.icon.icon-plus)
     -2:06.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:03.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -2:00.0 click (div.config-menu)
     -0:47.5.0 advanced-open-file:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-minimal-ui)
     -0:46.7.0 click (atom-panel.modal.overlay.from-top)
     -0:46.5.0 advanced-open-file:toggle (atom-text-editor.editor.mini.is-focused)
  5x -0:27.6.0 advanced-open-file:autocomplete (atom-text-editor.path-input.editor.mini.is-focused)
  3x -0:18.4.0 core:backspace (atom-text-editor.path-input.editor.mini.is-focused)
  2x -0:17.5.0 advanced-open-file:autocomplete (atom-text-editor.path-input.editor.mini.is-focused)
 34x -0:09.2.0 core:backspace (atom-text-editor.path-input.editor.mini.is-focused)
     -0:04.7.0 editor:consolidate-selections (atom-text-editor.path-input.editor.mini.is-focused)
     -0:04.7.0 core:cancel (atom-text-editor.path-input.editor.mini.is-focused)
     -0:00.8.0 click (a.stack-toggle)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "background-tips",
      "welcome",
      "language-lua",
      "about",
      "deprecation-cop",
      "incompatible-packages",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-java",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-ruby-on-rails",
      "language-source",
      "language-toml",
      "link",
      "package-generator",
      "update-package-dependencies",
      "language-perl",
      "language-property-list",
      "emmet",
      "metrics",
      "autocomplete-emojis",
      "Remote-FTP",
      "styleguide",
      "ex-mode",
      "archive-view",
      "autocomplete-atom-api",
      "keybinding-resolver",
      "release-notes",
      "quick-query",
      "pigments",
      "vim-mode",
      "dev-live-reload",
      "exception-reporting",
      "open-on-github",
      "spell-check",
      "timecop"
    ],
    "themes": [
      "one-minimal-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.12.0
atom-autocomplete-php, v0.18.1
autocomplete-php, v0.3.7
docblockr, v0.7.3
editorconfig, v1.2.2
file-icons, v1.6.11
language-puppet, v0.15.0
monokai, v0.18.0
one-minimal-ui, v0.0.0
php-extract-method, v0.2.0

# Dev
No dev packages
```
