### ISSUE TITLE
Hitting [esc] should close popup

### ISSUE THREAD

**Issue by ProLoser** [Osmose/advanced-open-file#51]
I'd like to be able to cancel the popup by hitting esc which doesn't seem to be possible currently.

**Comment by Osmose** [comment]
Thanks for the report, but I can cancel the popup with Esc no problem. What OS are you on?

**Comment by ProLoser** [comment]
Mac

**Comment by Osmose** [comment]
Hmmm. Have you bound the `core:cancel` action to a key besides Esc? Otherwise I can't imagine why it wouldn't work.

I'd suggest using the keybinding resolver, but hitting Esc just makes it exit. :disappointed:

**Comment by Osmose** [comment]
I'm going to close this since I can't replicate it and it hasn't seen a response, but if you or anyone else is still experiencing this and have more info on why it might not be working, feel free to reopen.
