### ISSUE TITLE
Advanced rename file

### ISSUE THREAD

**Issue by ProLoser** [Osmose/advanced-open-file#52]
Would be nice to replace the existing rename file functionality with this one. It would look identical to atom's built-in version except it would have folder dropdowns.

**Comment by Osmose** [comment]
That sounds like a good idea for a separate plugin, perhaps a fork of this, or maybe if we abstracted out the file dialog and used it in both packages. But I don't think it's something to be added to this package. Thanks for the suggestion, though!
