### ISSUE TITLE
Keyboard shortcut to open directory

### ISSUE THREAD

**Issue by ericdill** [Osmose/advanced-open-file#61]
Great library! I love this plugin.  Definitely makes atom way more usable. :+1: 

I would love if there was a way to open up a directory via a keyboard shortcut instead of clicking the "+" icon.  Is that a feature that is already built in and I just missed it?

**Comment by Osmose** [comment]
Thanks for the suggestion!

That does not exist and it totally should. I'll see about getting to it when I can.

**Comment by ericdill** [comment]
Ok awesome!  If I knew coffeescript I would totally open a PR, but alas I am just a python dev.

**Comment by Osmose** [comment]
No problem. I'm both! :P

I'm nearing the end of refactoring the project anyway, so a PR right now is not worth the effort since everything is going to be be replaced.

**Comment by ericdill** [comment]
Ha! Well now I sure am glad I did the lazy thing and just opened an issue instead of getting a rudimentary understanding of coffee script and making a PR :)

Good luck with the refactor.

**Comment by Osmose** [comment]
Just a note for future implementation, there's an existing `application:add-project-folder` command that we can probably co-opt for this. On OSX it defaults to Shift-Cmd-O.

**Comment by Osmose** [comment]
Fixed on master, and will go out with the next release. Thanks again for the suggestion!

**Comment by ericdill** [comment]
Brilliant. Finally circled back to this.  (I've been using PyCharm for a little while).  Turns out that the default keybind of `ctrl-alt-o` for toggling advanced-open-file on Linux shadows the `application:add-project-folder` command.  I had to remap it to `alt-shift-o`, but that was easy.  Thanks for adding this!
