### ISSUE TITLE
Promise.defer causing crashes with other packages

### ISSUE THREAD

**Issue by JaKXz** [Osmose/advanced-open-file#68]
It seems that `advanced-open-file` polyfilling the `global.Promise` object is breaking other packages, namely atom-typescript. See: TypeStrong/atom-typescript#709

**Comment by Osmose** [comment]
Oh shiiiiiiii

Thanks for the report! Guess we can't use the Babel polyfill directly. Oh well!

**Comment by JaKXz** [comment]
Thanks!

**Comment by Osmose** [comment]
@NoctisHsu This fixes the issue for me, can you confirm if this fixes it for you as well? I just released 0.12.1 with the fix.

**Comment by NoctisHsu** [comment]
@Osmose Yes, It's working fine with atom-typescript package now.
Thanks a lot  :)

**Comment by Osmose** [comment]
No problem, glad to help. Thanks for verifying. :D
