### ISSUE TITLE
Scroll to the last character on toggle

### ISSUE THREAD

**Issue by ineu** [Osmose/advanced-open-file#7]
`advanced-open-file:toggle` uses current path, which can be longer than textbox's length. In this case cursor is not visilble, you have to press some key (e.g. right arrow) to reveal it.
I propose to always scroll to the last character. This would not have negative effects in case of short path, but would be better user experience for paths longer than input box.

**Comment by Osmose** [comment]
I agree and would love to do this, but I'm having trouble finding a way to actually make it scroll. The cursor itself is already at the end but nothing I can find online points to a good way to get the input to visually show the end of the text. :\

**Comment by Osmose** [comment]
I've [asked for help on the Atom packages forum](https://discuss.atom.io/t/scroll-atom-text-editor-to-end-of-long-text/18771), hopefully someone will have an idea of what to try.

**Comment by Osmose** [comment]
A very helpful reply led me to the fix. Hope that helps!

**Comment by ineu** [comment]
That works, thanks a lot!
