### ISSUE TITLE
Modal partly out of view for certain themes

### ISSUE THREAD

**Issue by Traverse** [Osmose/advanced-open-file#72]
I think this is mostly an issue with certain ui themes for example when I'm using [native-ui](https://github.com/fv0/native-ui) and I open the advanced-open-file modal it sticks out of view at the bottom because the modal doesn't open at the top like with most themes.

![example-adv-open-file](https://cloud.githubusercontent.com/assets/7240988/11181946/156c20b0-8c67-11e5-8b52-dde442eac2a0.png)

I guess it would be preferable to have a checkbox to have different behavior for if the modal is at the top or not or if you have a better idea that would be fine as well.

**Comment by Osmose** [comment]
Thanks for the report. Does it still scroll all the way or is it actually cut off at the bottom?

I wonder if maybe a fix in your personal stylesheet is the best fix.

**Comment by Traverse** [comment]
It does scroll but it gets cut off so you can't see all the files. I can understand that you might want to hold of with trying to fix this since it's not like every theme has this issue, it is however a good idea to implement something to fix this for a better user experience because I don't think telling every user that might have this issue to put a fix in their personal stylesheet is a good solution because Atom has a diverse user group. A simple fix would be to use a checkbox to set  `max-height` to something like 300px on `.list-group`.
