### ISSUE TITLE
No UI for setting: Create Directories

### ISSUE THREAD

**Issue by clayreimann** [Osmose/advanced-open-file#77]
<img width="818" alt="screen shot 2015-12-05 at 8 23 29 am" src="https://cloud.githubusercontent.com/assets/930039/11608248/87a550f4-9b29-11e5-9de4-1ca75d293e58.png">

**Comment by Osmose** [comment]
Thanks for the report!

This is really weird. I see the setting fine locally; I even created a fresh profile and installed the package and saw the setting. Did you restart Atom between updating the package and viewing the preferences panel? I could totally see a situation where the preferences pane doesn't get refreshed or re-rendered while Atom is still open after an update.

**Comment by clayreimann** [comment]
Just an aberration caused by not restart Atom.
