### ISSUE TITLE
Nitpicking pixels on input field.

### ISSUE THREAD

**Issue by JesseLeite** [Osmose/advanced-open-file#79]
I notice a few really small styling inconstancies with advanced-open-file's input field, versus other input fields in Atom (ie. Command Palette, CMD-F find and replace, etc.)

Advanced Open File:
![example](http://b3.ms/Emy9gdQRAkRo)

Command Palette:
![example2](http://b3.ms/P5DAv4ayMgEp)

Also, the border on the left and right of the input seems thinner.

I inspected your styles, and I notice you're using flex.  I'm not much help as I don't know much about flex, otherwise I'd submit PR.

Sorry for nitpicking pixels here :D  I really do love this package... Thank you for all your work <3

**Comment by Osmose** [comment]
omg is this why there's that gap below the cursor

can i really finally get rid of that

yesssssssssss

(Thanks for the report!)

**Comment by JesseLeite** [comment]
Haha :)  Not sure if flex is affecting that border width on left and right as well?  Do you see what I'm talking about there?

**Comment by Osmose** [comment]
Should be fixed in master. I'm not 100% sure why a flex value of `0` was the solution, but it was. Oh well!

Will try to make a release within the next week or so that will include the fix. Thanks again for filing the issue. :D

**Comment by JesseLeite** [comment]
No problem, and thank you :)
