### ISSUE TITLE
Create split panes

### ISSUE THREAD

**Issue by alexfedoseev** [Osmose/advanced-open-file#82]
E.g. on `cmd-k right` create split pane on the right from current active pane as it works in fuzzy finder.

I tried to add keybinding:

```cson
'.advanced-open-file atom-text-editor':
  'cmd-k right': 'pane:split-right'
```

But it doesn't work.

**Comment by Osmose** [comment]
Thanks for the report!

I've never heard of this before and just tried it, that's a cool shortcut! I'm 80% sure I'm down with adding this, but I'd like to play around with it once it's implemented a tiny bit to see how it feels.

**Comment by alexfedoseev** [comment]
Great! Thanks for your work :+1:

**Comment by Osmose** [comment]
This should be working in master, and should be included in a release pretty soon. If you can pull down master (or just the latest update if it's already released when you read this) and let me know if it works well for you I'd really appreciate it. :D

**Comment by alexfedoseev** [comment]
@Osmose Just tested it out — works like a charm! Thanks!

P.S. There is one more keybinding in tree-view that can be useful in this package: when file is selected user can hit `Cmd-1` and it will be opened in split `#1`, `Cmd-2` -> in split `#2` and so on.
