### ISSUE TITLE
Option to add to tree-view as a project folder

### ISSUE THREAD

**Issue by eboracus** [Osmose/advanced-open-file#9]
Would it be possible to implement an 'Add Project Folder...' option. Maybe as a toggle on the panel itself that can allow for opening a folder (or the parent folder if opening a file) as a project folder on the tree-view. Greyed out when navigating in an already open project folder.

**Comment by Osmose** [comment]
I like this idea; maybe an icon on the right side of each path that adds it? I'm okay with limiting this to mouse-only since it's something that presumably doesn't happen very often.

**Comment by eboracus** [comment]
Awesome. Yes I think that's sensible as it would be a, relatively, rare event. On that note, I was thinking it'd be good for the plus icon to not stand out and draw focus too much, but maybe it would be even better if it only appeared for the currently highlighted folder so as to not swamp the panel view and have lots of +'s for directories with many folders. Guess it depends how 'busy' it actually looks though so what ever you think is best.

**Comment by Osmose** [comment]
For reference, this is what the current PR looks like, using the "subtle" theme color. I'm okay with it.

<img width="626" alt="screen shot 2015-08-01 at 8 39 19 pm" src="https://cloud.githubusercontent.com/assets/193106/9024614/7cfeebdc-388d-11e5-8627-78159dda93d0.png">

**Comment by eboracus** [comment]
Yes, should've actually waited to post, as I got a chance to pull it down and take a look at it after. Works great, couldn't see any issues, and I agree that it looks pretty good 'in use'. Really nice.

**Comment by Osmose** [comment]
Released in 0.8.2 (along with file icon support which I've wanted for a while, yay!). :D
