### ISSUE TITLE
aof sometimes loses focus when selecting files outside project

### ISSUE THREAD

**Issue by artagnon** [Osmose/advanced-open-file#99]
I'm trying hard to get reproduction steps for this. In short, when I have nothing selected, and hit RET (with something selected or otherwise), focus moves from the dialog to the editor, and I have to use the mouse to restore focus. This doesn't happen terribly often, but it's a terrible annoyance.

Any clues as to what might be the problem?

**Comment by Osmose** [comment]
No idea, that sounds really weird. I'll see if I can replicate myself but consistent replication steps would be super-useful.

**Comment by Osmose** [comment]
Any news? I'm wondering if a custom theme or another package might be causing the issue?

One thing I've seen but never bothered with is moving between Atom windows, like a devtools window, can sometimes cause focus on the dialog to be lost. I'm not sure there's much we can do about that without taking over more of the window than I'd like, and it's pretty easy to just click inside the text input or click outside to dismiss the dialog.

**Comment by artagnon** [comment]
Let's mark this not-reproducible and close this issue until we have an actionable item.

**Comment by Osmose** [comment]
Righto! Thanks again.
